### ISSUE TITLE
failed to bring up cpu-1

### ISSUE THREAD

**Issue by Developer-jin** [minos-project/minos-hypervisor#1]
fvp平台，smp_cpu_up()调用smc到EL3后没法启动cpu1,请问您遇到过吗？

**Comment by minos-project** [comment]
我这边没有，可以把你的fvp配置选项以及以及atf的版本发我看看。

**Comment by Developer-jin** [comment]
FVP配置：
`FVP_Base_RevC-2xAEMv8A  -C pctl.startup=0.0.0.0 -C bp.secure_memory=0  -C bp.tzc_400.diagnostics=1 -C cluster0.NUM_CORES=4 -C cache_state_modelled=1                                    -C cluster0.cpu0.RVBAR=0x04020000 -C cluster0.cpu1.RVBAR=0x04020000 -C cluster0.cpu2.RVBAR=0x04020000 -C cluster0.cpu3.RVBAR=0x04020000 -C bp.hostbridge.userNetPorts="8022=22" -C bp.hostbridge.userNetworking=true -C bp.dram_size=8 -C bp.smsc_91c111.enabled=true -C bp.virtioblockdevice.image_path=sd.img --data cluster0.cpu0=bl31.bin@0x04020000 --data cluster0.cpu0=fdt.dtb@0x83e00000 --data cluster0.cpu0=Image@0x80080000 --data cluster0.cpu0=minos.bin@0xc0000000 --cadi-server`
ATF：v1.5
非常感谢～

**Comment by minos-project** [comment]
ATF中的手册有提到:
NOTE: The FVP_Base_RevC-2xAEMv8A FVP only supports shifted affinities, which is not compatible with legacy GIC configurations. Therefore this FVP does not support these legacy GIC configurations.

shifted affinities字面意思上看，这个Model中 MPIDR_EL1寄存器和别的CPU可能有差别, 这样会影响到cpuid的计算，可能当前MINOS没有考虑到这种case。我安装的DS版本中没有 FVP_Base_RevC-2xAEMv8A FVP这个model, 你可以看下这个MPIDR_EL1寄存器的值, 是否是这个原因。

另外，建议你使用 FVP_Base_AEMv8A 这个模型。当然欢迎测试更多的模型，并一同fix问题。

**Comment by minos-project** [comment]
You can sync the latest code , this issue has been fixed

please enable the macro CONFIG_MPIDR_SHIFT in config/fvp/fvp_config.h
