### ISSUE TITLE
"Compile ARM Trusted Firmware" error

### ISSUE THREAD

**Issue by chenbd** [minos-project/minos-hypervisor#11]
`make PLAT=fvp RESET_TO_BL31=1 ARM_LINUX_KERNEL_AS_BL33=1 PRELOADED_BL33_BASE=0xc0000000 ARM_PRELOADED_DTB_BASE=0x83e00000` outputs the following error with master branch:

  PP      bl1/bl1.ld.S
  LD      build/fvp/release/bl1/bl1.elf
aarch64-linux-gnu-ld.bfd: build/fvp/release/bl1/bl1.elf: Not enough room for program headers, try linking with -N
aarch64-linux-gnu-ld.bfd: final link failed: Bad value

using v1.5 tag no such issue.

**Comment by minos-project** [comment]
It seems there are config error in the lds for ATF the image sizeFor ATF. You may issue a bug to the ATF project.

And for ATF, I only test version 1.5.

VERSION_MAJOR                   := 1
VERSION_MINOR                   := 5

**Comment by chenbd** [comment]
Issue opened at: [675](https://github.com/ARM-software/tf-issues/issues/675)

**Comment by chenbd** [comment]
PR #13  opened, this issue can be fixed with `ENABLE_PIE=0`.
