### ISSUE TITLE
FVP boot with error: dtb address is 0, invalid dtb address

### ISSUE THREAD

**Issue by chenbd** [minos-project/minos-hypervisor#12]
Hello,

I follow the FVP guide and build all related module.
When i run
`/usr/local/DS-5_v5.29.2/bin/FVP_Base_AEMv8A               \
     -C pctl.startup=0.0.0.0                                     \
     -C bp.secure_memory=0                                       \
     -C cluster0.NUM_CORES=4                                     \
     -C cache_state_modelled=1                                   \
     -C cluster0.cpu0.RVBAR=0x04020000                           \
     -C cluster0.cpu1.RVBAR=0x04020000                           \
     -C cluster0.cpu2.RVBAR=0x04020000                           \
     -C cluster0.cpu3.RVBAR=0x04020000                           \
     -C bp.hostbridge.userNetPorts="8022=22"                     \
     -C bp.hostbridge.userNetworking=true                        \
     -C bp.dram_size=8                                           \
     -C bp.smsc_91c111.enabled=true                              \
     -C bp.virtioblockdevice.image_path=sd.img                   \
     --data cluster0.cpu0=bl31.bin@0x04020000                    \
     --data cluster0.cpu0=fdt.dtb@0x83e00000                     \
     --data cluster0.cpu0=Image@0x80080000                       \
     --data cluster0.cpu0=minos.bin@0xc0000000                   \
     --log fvp.log
`
minos panic with error: dtb address is 0.
How to fix this issue?

**Comment by minos-project** [comment]
If you add ARM_PRELOADED_DTB_BASE=0x83e00000 flag to compile ATF, the dtb address will passed from ATF to Minos fixed with 0x83e00000, even if you do not add --data cluster0.cpu0=fdt.dtb@0x83e00000.

So for this issue, the ATF seems did not compiled correctly.  you need check this.

**Comment by chenbd** [comment]
I use ATF from source, at `commit ed8112606c54d85781fc8429160883d6310ece32`, I also checked the release of ATF, v1.5 release using the same commit and I do not see any error when compiling ATF.

**Comment by minos-project** [comment]
this issue seems is: ATF did not set register x0 for dtb address correctly before starting minos, right?
 ------- YES

For ATF, I am using the commit at 776ba05a4718389ef4a35ec3f6b837be3cc39f54, you can try this commit.

**Comment by chenbd** [comment]
Great! it works now, using ATF commit at `776ba05a4718389ef4a35ec3f6b837be3cc39f54`.
Thanks a lot.

**Comment by chenbd** [comment]
ATF using master branch with `ENABLE_PIE=0` works too.
