### ISSUE TITLE
why memset's first param force cast to "char *"?

### ISSUE THREAD

**Issue by chenbd** [minos-project/minos-hypervisor#21]
guess it should be "void *".

**Comment by minos-project** [comment]
the definition of  memset  in include/minos/string.h is 
/************************************************
char *strchr(const char *src, char ch);
void memset(void *base, char ch, int size);
void *memmove(void *dest, const void *src, size_t n); 
************************************************/

the reason why some code force cast to "char *" is : Historical issues :)
