### ISSUE TITLE
Does hypervisor run with  Foundation_Platform?

### ISSUE THREAD

**Issue by chenbd** [minos-project/minos-hypervisor#27]
I run with the following command:
`
/usr/local/DS-5_CE_v5.29.1/bin/Foundation_Platform  \
     --cores=4                                      \
     --block-device=sd.img                          \
     --data=bl31.bin@0x04020000                     \
     --data=fdt.dtb@0x83e00000                      \
     --data=Image@0x80080000                        \
     --data=minos.bin@0xc0000000
`

And output is:
 Fast Models [11.4.35 (Jun 18 2018)]
Copyright 2000-2018 ARM Limited.
All Rights Reserved.

terminal_0: Listening for serial connection on port 5000
terminal_1: Listening for serial connection on port 5001
terminal_2: Listening for serial connection on port 5002
terminal_3: Listening for serial connection on port 5003

Seems it is running but can not see terminal window which output booting logs.
BTW, I found this "
If no terminal or program is connected to the port when data is output from the UART, a terminal is started automatically." from 
https://developer.arm.com/docs/dui0677/latest/programming-reference/uarts

**Comment by minos-project** [comment]
Not test on Foundation Platform.

You need check the Foundation_Platform's UART controller and its MMIO address. If the UART is different from FVP, need to add the UART driver or change the MMIO base address.

**Comment by chenbd** [comment]
Hello,
I'm not sure how to check this, I found this in ATF:
at https://github.com/ARM-software/arm-trusted-firmware/blob/master/include/plat/arm/board/common/v2m_def.h#L79
/* PL011 UART related constants */
#define V2M_IOFPGA_UART0_BASE		UL(0x1c090000)
#define V2M_IOFPGA_UART1_BASE		UL(0x1c0a0000)
#define V2M_IOFPGA_UART2_BASE		UL(0x1c0b0000)
#define V2M_IOFPGA_UART3_BASE		UL(0x1c0c0000)

Also in minos at https://github.com/minos-project/minos-hypervisor/blob/master/hypervisor/drivers/serial/serial.c#L38
#ifdef CONFIG_PLATFORM_FVP
	return  pl011_init((void *)0x1c090000, 24000000, 115200);
#endif
seems the address is the same, right?

**Comment by minos-project** [comment]
I think the system is hang in ATF.

You can build debug verion of ATF (DEBUG=1) to see the log.

**Comment by chenbd** [comment]
Yes, with the following command, I can see the terminal with boot log:
/usr/local/DS-5_CE_v5.29.1/bin/Foundation_Platform  \
    --cores=4                                       \
    --arm-v8.0                                      \
    --secure-memory                                 \
    --visualization                                 \
    --gicv3                                         \
    --data=build/fvp/release/bl1.bin@0x0             \
    --data=build/fvp/release/fip.bin@0x08000000      \
    --data=../linux-marvell/arch/arm64/boot/Image@0x80080000   \
    --data=../arm-fvp/fdt.dtb@0x83e00000                      \
    --data=../arm-fvp/minos.bin@0xc0000000

But minos panic with: dtb address is 0, invalid dtb address.
ATF built with `make PLAT=fvp PRELOADED_BL33_BASE=0xc0000000 ARM_PRELOADED_DTB_BASE=0x83e00000 ENABLE_PIE=0 all fip`

**Comment by chenbd** [comment]
After patch ATF with valid dtb address, minos can boot now, but crash at: `fvp_time_init`.
