### ISSUE TITLE
How to create more than one static vm sharing with same dtb and Image?

### ISSUE THREAD

**Issue by chenbd** [minos-project/minos-hypervisor#28]
Hello,
Tried using Foundation Platform without success.

**Comment by lemin9538** [comment]
I think you need add some command like this:
--data cluster0.cpu0=Image@0x80080000 

But actullay, the static VM feature is not fully support yet, I do not test the feature till now.
In addition, the related driver for static VM is under developing.

**Comment by chenbd** [comment]
Hello,

Thanks for you information, I'm using Foundation Platform(because it does not need license file) and seems `cluster0.cpu0` not supported by Foundation Platform.

**Comment by lemin9538** [comment]
Email to me (lemin9538@163.com), I will give your some detail on FVP. You know it :)

**Comment by chenbd** [comment]
@lemin9538 Thanks for your advice.
Currently Foundation Platform works with minos hypervisor and linux can boot successfully on hypervisor.
So i can use  Foundation Platform for now and will reach for your help if must switch to FVP.
