### ISSUE TITLE
there's no sd.img when Create new guest VM

### ISSUE THREAD

**Issue by shensjh** [minos-project/minos-hypervisor#29]
![微信图片_20190625203434](https://user-images.githubusercontent.com/20653289/60098675-b0426b00-9788-11e9-9f04-bc0f18ae54d4.png)

hi，
I am running on the Raspberry Pi 3B. From the above logs, it seems like I have successfully logged into debian.
There is such a problem: When I created gusest vm, indicated that there is no /home/jiangxianxu/sd.img in sdcard.

What effect will this have? Did I create a guest vm successfully? Where can I download this sd.img?
Is this address that i can get the file? # wget http://leyunxi.com/static/sd.img, response 404

**Comment by minos-project** [comment]
The below commands is to create a bigger block image with 2G size and LAMP support. All the tools and commands are from Linaro, and test on Ubuntu 14.04, more information can refers to Linaro release https://releases.linaro.org/openembedded/aarch64/15.08/

    # sudo add-apt-repository ppa:linaro-maintainers/tools
    # sudo apt-get update
    # sudo apt-get install linaro-image-tools
    # wget https://releases.linaro.org/openembedded/aarch64/15.08/linaro-image-lamp-genericarmv8-20150729-758.rootfs.tar.gz
    # wget https://releases.linaro.org/openembedded/aarch64/15.08/hwpack_linaro-vexpress64-rtsm_20150821-726_arm64_supported.tar.gz
    # linaro-media-create --dev fastmodel --output-directory fastmodel --image_size 2048M --hwpack hwpack_linaro-vexpress64-rtsm_20150821-726_arm64_supported.tar.gz --binary linaro-image-lamp-genericarmv8-20150729-758.rootfs.tar.gz

**Comment by shensjh** [comment]
TKS！
 seems like i have created gust vm successfully:

> [INFO ] boot image infomation :
[INFO ] magic        - ANDROID!
[INFO ] kernel_size  - 0x960600
[INFO ] kernel_addr  - 0x80080000
[INFO ] ramdisk_size - 0x104e21
[INFO ] ramdisk_addr - 0x83000000
[INFO ] dtb_size     - 0xf3b
[INFO ] dtb_addr     - 0x83e00000
[INFO ] tags_addr    - 0x0
[INFO ] page_size    - 0x800
[INFO ] name         - 
[INFO ] cmdline      - console=hvc0 loglevel=8 consolelog=9
[INFO ] create new vm *
[INFO ]         -name       : elinux64
[INFO ]         -os_type    : linux
[INFO ]         -nr_vcpu    : 2
[INFO ]         -bit64      : 1
[INFO ]         -mem_size   : 0x6000000
[INFO ]         -mem_base  : 0x80000000
[INFO ]         -entry      : 0x0x80080000
[INFO ]         -setup_data : 0x0x83e00000
[DEBUG] load kernel image: 0x80000 0x800 0x960600
jiangxianxu@debianOnRpi:~$ [INFO ] virtio-mmio : 0x0x40000000 0x0x7fa7f7d000 0x1000
[DEBUG] vdev : irq-64 hpa-0x0x7fa7f7d000 gva-0x0x40000000
[INFO ] ***[  261.746315] tun: Universal TUN/TAP device driver, 1.6
[     268.487565 00] INF create vgicv2 for vm-1
[     268.491178 00] ERR vgicv2 address 0x2f000000 0x10000 0x2c000000 0x2000
[     268.497975 00] INF create virq_chip arm,cortex-a15-gic successfully
[     268.504871 00] INF create virtual watchdog for vm-1
[     268.510238 00] INF create virtual rtc for vm-1
[     268.514992 00] INF create virtio-mmio device for vm-1
[     268.520355 00] INF create virtio-mmio device for vm-1
[     268.525731 00] INF create virtio-mmio device for vm-1
[  261.822556] register event-10 irq-32
[  261.830664] register event-12 irq-35
[     268.560286 00] INF vm-1 vcpu-0 affnity to pcpu-2
[     268.564446 00] INF vm-1 vcpu-1 affnity to pcpu-0
`********************************************`
[INFO ] virt-console backend redirected to /dev/pts/0
[INFO ] ***********************************************
[DEBUG] vdev : irq-65 hpa-0x0x7fa7f7d400 gva-0x0x40000400
[DEBUG] vdev : irq-66 hpa-0x0x7fa7f7d800 gva-0x0x40000800
[INFO ] open of tap device tap0 success!
[INFO ] add cmdline - console=hvc0 loglevel=8 consolelog=9 root=/dev/vda2 rw
[INFO ]         - delete cpu@2
[INFO ]         - delete cpu@3
[INFO ]         - delete cpu@4
[INFO ]         - delete cpu@5
[INFO ]         - delete cpu@6
[INFO ]         - delete cpu@7
[DEBUG] found 1 rsv memory region
[DEBUG] add rsv memory region : 0x80000000 0x10000
[INFO ] setup memory 0x0 0x80 0x0 0x6
[INFO ] vm gic type is gic-v2
[INFO ] add vdev success addr-0x40000000 virq-64
[INFO ] update cmdline -  earlycon=virtio_console,0x40000000 console=hvc0 loglevel=8 consolw
[INFO ] add vdev success addr-0x40000400 virq-65
[INFO ] add vdev success addr-0x40000800 virq-66
[     268.915386 02] INF request vcpu on
[     268.918301 02] INF vcpu-1 of vm-1 power on from vm suspend 0x00000000800829d0

`jiangxianxu@debianOnRpi:~$` 


A new problem: I can't log in ssh. like this:

![1841554612](https://user-images.githubusercontent.com/20653289/60245483-442e4700-98ef-11e9-8004-684089189b08.jpg)

**Comment by minos-project** [comment]
Does you desktop at the same network with your RPI? You can ping your RPI to see whether the network is ok.

**Comment by shensjh** [comment]
as you said, I have been able to login remotely after connecting to the same network.

TKS!
