### ISSUE TITLE
I cannot found arch/arm64/boot/dts/broadcom/bcm2837-rpi-3-b-plus.dtb file

### ISSUE THREAD

**Issue by kimyw3007** [minos-project/minos-hypervisor#3]
Hi 

i have a some question of installing to minos on rasp Pi 3+

I follow up your guide and i tried to find arch/arm64/boot/dts/broadcom/bcm2837-rpi-3-b-plus.dtb
 in https://github.com/minos-project/linux-raspberry.git

but there was no arch/arm64/boot/dts/broadcom/bcm2837-rpi-3-b-plus.dtb after build

i want to find this

and actually i want to know that is it ok to copy bcm2837-rpi-3-b.dtb ( without plus) than bcm2837-rpi-3-b-plus.dtb ?? 

Thank you for reading!

**Comment by minos-project** [comment]
no bcm2837-rpi-3-b.dtb may have some issue. have you done all the below steps:

 # git clone https://github.com/minos-project/linux-raspberry.git && cd linux-raspberry
 # git checkout -b minos-rpi-4.20-y origin/minos-rpi-4.20-y
 # make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcmrpi3_defconfig
 # make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image -j8
 # make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules dtbs -j8

bcm2837-rpi-3-b-plus.dtb will generate at arch/arm64/boot/dts/broadcom after you finish below command

 # make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules dtbs -j8

**Comment by kimyw3007** [comment]
i solved this but.. i face another problem when i did "sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_install INSTALL_MOD_PATH=/media/zac/711a5ddf-1ff4-4d5a-ad95-8b9b69953513"

then I faced below line

![img_4557](https://user-images.githubusercontent.com/45417960/51010381-6c232b80-1597-11e9-8469-5ae69ca36369.jpg)

but i already install aarch64-linux-gnu- and i completed check to work this in ubuntu shell mode

please notice what happend to me

Thank you for reading

**Comment by kimyw3007** [comment]
I already did all of this and i could see that(aarch64-linux-gnu-gcc) worked well

but it happend I have no idea why it happened to me T.T

Thank you for reading

**Comment by kimyw3007** [comment]
oh ok. thank you i am using ubuntu 18.04 so i will change my linux environment and maybe you need to modify this gcc version in install process thank you for everything

**Comment by minos-project** [comment]
Thanks for you remind, I will change the README.md to change the gcc version to 7.2.1

I think gcc version 7.2.1 20171011 may fix your problem. you can try it first. :)

**Comment by kimyw3007** [comment]
Im glad to use this 
thank you fast feedback and explain
i will try again! Thank you for evertything

**Comment by minos-project** [comment]
It is very strange. 

But I think you can ignore this warning. Since from the picture, all the modules have been successfully installed to you SD card.

you can ignore it temporary.
