### ISSUE TITLE
Run hypervisor with Foundation_Platform

### ISSUE THREAD

**Issue by LY-Dora** [minos-project/minos-hypervisor#31]
I try to run hypervisor with Foundation_Platform, and I refer to the contents of  [#27 issue](https://github.com/minos-project/minos-hypervisor/issues/27).

I run with the following command:

> ~/ARM/FM000-KT-00035-r11p7-30rel0/Foundation_Platformpkg/models/Linux64_GCC-4.9/Foundation_Platform --cores=4 --arm-v8.0 --no-secure-memory --network=nat --network-nat-ports=8022=22 --no-visualization --gicv3 --data=bl1.bin@0x0 --data=fip.bin@0x08000000 --data=Image@0x80080000 --data=fdt.dtb@0x83e00000 --data=minos.bin@0xc0000000 --block-device=sd.img

And the output is:
Fast Models [11.7.30 (May 29 2019)]
Copyright 2000-2019 ARM Limited.
All Rights Reserved.

terminal_0: Listening for serial connection on port 5000
terminal_1: Listening for serial connection on port 5001
terminal_2: Listening for serial connection on port 5002
terminal_3: Listening for serial connection on port 5003

At the same time, FVP terminal_0 will appear, its content is:

> NOTICE:Booting Trusted Firmware
NOTICE:BL1 v2.1(release):v2.1-558-g44e8d5e
NOTICE:BL1: Built : 22:24:38,Aug 24 2019
NOTICE:BL1: Booting BL2
NOTICE:BL2 v2.1(release):v2.1-558-g44e8d5e
NOTICE:BL2: Built : 22:24:40,Aug 24 2019

Seems it is running but can not establish a ssh session.
The log of ssh is:

> dora@dora-XPS-8930:~/minos-workspace/arm-fvp$ ssh -p 8022 root@127.0.0.1 -v
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /home/dora/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 8022.
debug1: Connection established.
debug1: identity file /home/dora/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/dora/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/dora/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/dora/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/dora/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/dora/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/dora/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/dora/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8

I just started using fvp, I don't know how to debug this problem.
Looking regards to your help.

**Comment by minos-project** [comment]
What's the Ubuntu version do you use?

I found there are SSH issues (can not connect to fvp) on ubuntu-16.04, but on ubuntu-14.04, everything is ok.

**Comment by LY-Dora** [comment]
I use ubuntu-16.04.

The hypervisor did not work normally because the patch of 'arm_bl31_setup.c' mentioned in #27 issue was added incorrectly.If the two patches was added correctly, the problem will
be fixed.
