### ISSUE TITLE
system can not reboot if add virtio-net device

### ISSUE THREAD

**Issue by minos-project** [minos-project/minos-hypervisor#34]
reproduce steps:

1 - create a vm using below command:
     sudo ./mvm -c 2 -m 84M -i boot64.img -n elinux -t linux -b 64 -v -d --earlyprintk --gicv2 \
    -C "console=hvc0 loglevel=8 consolelog=9 rw" \
    -V virtio_net,tap0 \
    -V virtio_console,@pty:

2 - using minicom to login to the vm
3 - reboot the vm

the log stoped in linux_load_bootimage and no more log output

**Comment by lemin9538** [comment]
Fixed at the master branch.

This reason is that when reset, mvm acess the Virtqueue after the pointer of Virtqueue is set to NULL.
