### ISSUE TITLE
mvm:error - load kernel image failed

### ISSUE THREAD

**Issue by chengshuyi** [minos-project/minos-hypervisor#35]
Hi! I am trying hypervisor(master branch) on fvp platform. The host linux run successfully but guest os can not run. The program stop at `load_image` function in os_linux.c file. And the errno is 14. The detailed error message is `bad adress`. So `(char *)(vm->mmap + load_offset)` may be a null or invalid buffer pointer. However i have checked the va->ipa->pa which is not wrong.

```
va is : 0xffff9be00000
ipa is : 0x2080000000
pa is : 0xc0800000
```

And i try to access the pointer of vm->mmap, the program stoped without any error message. I don't know why `(char *)(vm->mmap + load_offset)` is a null or invalid buffer pointer.
Thanks for any advice!

**Comment by chengshuyi** [comment]
To determin wether the va->ipa is set correctly or not, i try to translate va to ipa in user space by accessing /proc/<pid>/pagemap file. 

```
when i try to translate va - 0xffff9be00000, the output is 0x0. 
when i try to translate va - 0xaaaac0789000(an example), the output is normal, 0x943f4000. 
```

Thus, the mmap function may be not right.

For the translation between va and ipa, see [here](https://stackoverflow.com/questions/5748492/is-there-any-api-for-determining-the-physical-address-from-virtual-address-in-li)

**Comment by chengshuyi** [comment]
fixed! 
the doubtful code link is [(pud_t *)pgd](https://github.com/minos-project/minos-linux-driver/blob/099154229752faffefa5a045d6a76f50fee9560c/minos/minos.c#L540) which located at minos-linux-drive repo.
- return (pte_t *)pmd_offset((pud_t *)pgd, addr);
+ return (pte_t *)pmd_offset(pud_offset(pgd,addr), addr);

**Comment by lemin9538** [comment]
Hi Shuyi,

What's the version of guest VM kernel do you use ?

**Comment by chengshuyi** [comment]
Hi, the version of host vm kernel is 4.14 and the guest vm kernel is [minos-sample](https://github.com/minos-project/minos-samples) repo.
