### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zhuzhizhan** [minos-project/minos-hypervisor#36]
make xxx_defconfig
make
Then error occur:
/home/zzz/code/minos-hypervisor/os/virt/resource.c:299: undefined reference to `create_mailbox'
/home/zzz/code/minos-hypervisor/os/virt/resource.c:299:(.text+0x8d8): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `create_mailbox'

**Comment by minos-project** [comment]
Fixed.
