### ISSUE TITLE
what's the difference between `minos-hypervisor` and `xen-arm`?

### ISSUE THREAD

**Issue by chenbd** [minos-project/minos-hypervisor#6]
Hello, 
This is a **interesting** project.
I'm curious  about the target or use case for this project.
Open source hypervisors like `xen` or `kvm`  already exist.
So What's the difference between `minos-hypervisor` and `xen-arm`?

**Comment by minos-project** [comment]
Hello
xen and kvm is mainly used on the servers.
The purpose of Minos project is to create a lightweight Hypervisor for mobile and embedded systems, and built to meets the unique needs of embedded IoT development.

**Comment by chenbd** [comment]
Currently i'm looking for a hypervisor solution for our Automotive product on i.MX 8 platform which may run Linux,Android and RTOS.

After a few days searching seems xen-arm is the first choice(jailhouse also under consideration).
And a few companies can provide solution based on xen-arm for Automotive.

That's why i want to know the difference between this project and xen-arm.
Have you compared with xen-arm, What's the Pros and Cons for this project?

Thank you.

**Comment by minos-project** [comment]
I did not do deep search on xen-arm

you mentioned that your product will use RTOS. So how high are the real-time requirements for your product? if you have high real-time requirements in your product, you need to test whether current xen-arm solution can meet your requirement.

The goal of Minos project is to create a Hypervisor for embedded system, so when design this hypervisor, there are some consideration of real-time.  In addition, Minos hypervisor is easy and small, can be easily porting to any ARMV8 platform, you can also DIY it easily to fit for your product's requirement. 

The Cons: Minos is young and  only one people working on it :)
